name: Build and Publish APK on Updates

on:
  push:
    branches: [main, work]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
  release:
    types: [published]

# 防止同一分支/標籤同時跑多個工作
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Set up Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3

      - name: Install platform-tools, platform 35, build-tools 35.0.0
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Compute short sha
        run: echo "SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Publish APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: sha-${{ env.SHORT_SHA }}
          name: "Build sha-${{ env.SHORT_SHA }}"
          commit: ${{ github.sha }}
          artifacts: app/build/outputs/apk/release/*.apk
          artifactContentType: application/vnd.android.package-archive
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
